version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
    links:
      - php
  php:
    build: .
    volumes:
      - "./:/var/www/html"